### ISSUE TITLE
导入库后，可以登陆，但首页面有抛错,没有任何面板

### ISSUE THREAD

**Issue by oslet** [hzwy23/hauth#1]
![_009](https://cloud.githubusercontent.com/assets/1573303/24942664/0c1dd960-1f85-11e7-80a1-bba4029ce213.png)

**Comment by oslet** [comment]
问题已解决，mysql5.7版本的原因，换成 5.5一切正常.

**Comment by hzwy23** [comment]
幸好你找出来了,不然我这边如果不换数据库,可能永远都找不到答案...
