### ISSUE TITLE
没有数据库表结构啊？？

### ISSUE THREAD

**Issue by xml4cn** [hzwy23/hauth#2]
初始化脚本里面只有insert 语句，没有表结构啊？

**Comment by hzwy23** [comment]
在hauth/script目录中,有个sql脚本,里边就是表结构和初始化数据.

**Comment by hzwy23** [comment]
已经测试,通过mysql提供的命令
mysql -uroot -p dbname < hauth/script/init_hauth.sql
dbname 是mysql数据库中已经存在的database
