### ISSUE TITLE
自定义样式

### ISSUE THREAD

**Issue by Hjingmo** [hzwy23/hauth#3]
如果要新增加一种自定义样式，请问要怎么弄呢？

**Comment by hzwy23** [comment]
样式,这个目前根据Metro.css中提供的样式, 选取了3中常规样式,
第一种是小正方形,对应的是tile,
第二种是长方形:tile tile-wide ,
第三种是大正方形:tile tile-large. 
如果需要在菜单- 主题设置中,样式下拉框中新增样式, 可以在views/hauth/res_info_page.tpl第525行,594行的select标签中,新增option, option的值,需要是已经存在css class.
