### ISSUE TITLE
建议采用专业的Casbin组件进行权限管理

### ISSUE THREAD

**Issue by hsluoyz** [hzwy23/hauth#8]
RT, https://github.com/casbin/casbin

**Comment by hzwy23** [comment]
大概了解了下您推荐的这个casbin,  个人感觉这个casbin挺不错的, 但是:"In Casbin, an access control model is abstracted into a CONF file based on the PERM metamodel" 这个casbin好像是使用配置文件,在进行权限,  我的项目中,经常动态调整权限配置, 如果使用文件的话, 个人感觉相较于数据库要麻烦一点. 如果理解不对的地方,请多多指教.

**Comment by hsluoyz** [comment]
你好，这个问题提的很好，这里其实有一个误区。这个CONF  file其实是模型文件，不是策略。在casbin里，模型和策略是分开的。模型是指一些更抽象的匹配规则，这个通常是不变的，放在CONF file里就好。而策略就是所具体管理的权限，casbin支持把策略放在文件或数据库里，或者哪里都不放，动态在内存里也可。

简单一点的回答就是casbin的权限配置，是可以放在数据库的，目前支持MySQL等RDBMS，还有Cassandra。

**Comment by hzwy23** [comment]
我再去研究研究casbin这个项目,  感谢赐教.  这个大哥, 有时间的话, 帮忙改进下权限控制这块.
3q

**Comment by hzwy23** [comment]
我再去研究研究casbin这个项目, 感谢赐教. 这位大哥, 有时间的话, 帮忙改进下权限控制这块.
3q
